services:
  mariadb:
    image: mariadb:11.8
    restart: on-failure
    hostname: mariadb
    ports:
      - '3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=karaplan
      - MARIADB_USER=karaplan
      - MARIADB_PASSWORD=KaraPlan123
      - MARIADB_ROOT_PASSWORD=Root123
  mysql:
    image: mysql:8.0
    restart: on-failure
    hostname: mysql
    ports:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=karaplan
      - MYSQL_USER=karaplan
      - MYSQL_PASSWORD=KaraPlan123
      - MYSQL_ROOT_PASSWORD=Root123
    profiles:
      - mysql
  postgresql:
    image: postgres:15
    restart: on-failure
    hostname: postgresql
    ports:
      - '5432'
    volumes:
      - postgresql-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=karaplan
      - POSTGRES_USER=karaplan
      - POSTGRES_PASSWORD=KaraPlan123
    profiles:
      - postgresql
  grafana:
    image: grafana/otel-lgtm:0.23.0
    restart: on-failure
    hostname: grafana
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
    volumes:
      - grafana-data:/data
    profiles:
      - grafana
volumes:
  mariadb-data:
  mysql-data:
  postgresql-data:
  grafana-data:
