create sequence "hibernate_sequence" start with 1 increment by 1;
create table "artist" ("CATALOG_ID" bigint unique, "CREATED_DATE" timestamp(6) with time zone, "ID" bigint not null, "UPDATED_DATE" timestamp(6) with time zone, "NAME" varchar(255) not null, primary key ("ID"));
create table "playlist" ("COMMENTS_COUNT" integer, "READ_ONLY" boolean, "SONGS_COUNT" integer, "CREATED_DATE" timestamp(6) with time zone, "DURATION" bigint, "FK_USER_CREATED" bigint, "FK_USER_UPDATED" bigint, "ID" bigint not null, "UPDATED_DATE" timestamp(6) with time zone, "ACCESS_KEY" varchar(255), "NAME" varchar(255) not null, primary key ("ID"));
create table "playlist_comment" ("CREATED_DATE" timestamp(6) with time zone, "FK_PLAYLIST" bigint not null, "FK_USER" bigint, "ID" bigint not null, "COMMENT" varchar(255) not null, primary key ("ID"));
create table "playlist_song" ("POSITION" integer, "CREATED_DATE" timestamp(6) with time zone, "FK_PLAYLIST" bigint not null, "FK_SONG" bigint not null, "FK_USER_CREATED" bigint, "FK_USER_UPDATED" bigint, "UPDATED_DATE" timestamp(6) with time zone, primary key ("FK_PLAYLIST", "FK_SONG"));
create table "playlist_user" ("FK_PLAYLIST" bigint not null, "FK_USER" bigint not null, primary key ("FK_PLAYLIST", "FK_USER"));
create table "song" ("COMMENTS_COUNT" integer, "PLAYLISTS_COUNT" integer, "SCORE" integer, "SCORE_DOWN" integer, "SCORE_UP" integer, "YEAR" integer, "CATALOG_ID" bigint unique, "CREATED_DATE" timestamp(6) with time zone, "DURATION" bigint, "FK_ARTIST" bigint, "ID" bigint not null, "UPDATED_DATE" timestamp(6) with time zone, "IMAGE" varchar(255), "NAME" varchar(255) not null, primary key ("ID"));
create table "song_comment" ("CREATED_DATE" timestamp(6) with time zone, "FK_SONG" bigint not null, "FK_USER" bigint, "ID" bigint not null, "COMMENT" varchar(255) not null, primary key ("ID"));
create table "song_vote" ("SCORE" integer not null, "CREATED_DATE" timestamp(6) with time zone, "FK_SONG" bigint not null, "FK_USER" bigint, "ID" bigint not null, primary key ("ID"), unique ("FK_SONG", "FK_USER"));
create table "user" ("CREATED_DATE" timestamp(6) with time zone, "ID" bigint not null, "UPDATED_DATE" timestamp(6) with time zone, "DISPLAYNAME" varchar(255) not null, "EMAIL" varchar(255), "FIRSTNAME" varchar(255), "FULLNAME" varchar(255), "LASTNAME" varchar(255), "LOCALE" varchar(255), "PROVIDER" varchar(255) not null, "USERNAME" varchar(255) not null, primary key ("ID"));
alter table if exists "playlist" add constraint "FKdauut0r7v06qde4io9fdql21r" foreign key ("FK_USER_CREATED") references "user";
alter table if exists "playlist" add constraint "FKxv554gtpvha7k7r78pxfmcpx" foreign key ("FK_USER_UPDATED") references "user";
alter table if exists "playlist_comment" add constraint "FKfe5to8iwev8faro6ft5ubwnb7" foreign key ("FK_PLAYLIST") references "playlist";
alter table if exists "playlist_comment" add constraint "FKe602eu848rd544duitve5fxq3" foreign key ("FK_USER") references "user";
alter table if exists "playlist_song" add constraint "FKbgiw7v5gldpgv7o0tco8n6sq6" foreign key ("FK_PLAYLIST") references "playlist";
alter table if exists "playlist_song" add constraint "FKhfb9nbm0vj5hl2lrh3fd89eh2" foreign key ("FK_SONG") references "song";
alter table if exists "playlist_song" add constraint "FKg4qtdvblduesgihhqqbe2xhhr" foreign key ("FK_USER_CREATED") references "user";
alter table if exists "playlist_song" add constraint "FKi1b61opysejchrx7fm7qxc8id" foreign key ("FK_USER_UPDATED") references "user";
alter table if exists "playlist_user" add constraint "FKg6696lrwf3aq85f8aforinfcp" foreign key ("FK_USER") references "user";
alter table if exists "playlist_user" add constraint "FKpuw87dwtocmfsilbopyqpf7wn" foreign key ("FK_PLAYLIST") references "playlist";
alter table if exists "song" add constraint "FK1gwfrf19crw1qou8iyfia8bwh" foreign key ("FK_ARTIST") references "artist";
alter table if exists "song_comment" add constraint "FKrjcfgcc7qrw3p744vtffw0iw9" foreign key ("FK_SONG") references "song";
alter table if exists "song_comment" add constraint "FKpixykrfye3dqb0wirx9yetiib" foreign key ("FK_USER") references "user";
alter table if exists "song_vote" add constraint "FKi5tbqu3y7a82qn02w07bgqn5y" foreign key ("FK_SONG") references "song";
alter table if exists "song_vote" add constraint "FKk3s2b5csobnxod1745cfuukkq" foreign key ("FK_USER") references "user";
